### ISSUE TITLE
如何搭建环境

### ISSUE THREAD

**Issue by paopaofish** [Rekoe/rk_svnadmin#2]
> 已经将代码下载到本地，数据库创建已经完成。可以运行并到登录界面。问题是：接下来如何使用？因为无法登录

1. 环境还有什么依赖？
     是不是需要在本地安装一个svn服务端？如何将svn服务端整合到这个管理系统中管理起来
2. 用户怎么创建配置？这个管理系统的用户的登录配置。

**Comment by Rekoe** [comment]
@paopaofish 
待我继续完善readme

**Comment by paopaofish** [comment]
@Rekoe 好

**Comment by paopaofish** [comment]
可以参考readMe了
